# Generated by Django 4.1.3 on 2022-11-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agosto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primeraSemana', models.IntegerField(verbose_name='Semana 1')),
                ('segundaSemana', models.IntegerField(verbose_name='Semana 2')),
                ('terceraSemana', models.IntegerField(verbose_name='Semana 3')),
                ('cuartaSemana', models.IntegerField(verbose_name='Semana 4')),
            ],
            options={
                'verbose_name': 'Agosto',
                'verbose_name_plural': 'Agosto',
            },
        ),
        migrations.CreateModel(
            name='Noviembre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primeraSemana', models.IntegerField(verbose_name='Semana 1')),
                ('segundaSemana', models.IntegerField(verbose_name='Semana 2')),
                ('terceraSemana', models.IntegerField(verbose_name='Semana 3')),
                ('cuartaSemana', models.IntegerField(verbose_name='Semana 4')),
            ],
            options={
                'verbose_name': 'Noviembre',
                'verbose_name_plural': 'Noviembre',
            },
        ),
        migrations.CreateModel(
            name='Octubre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primeraSemana', models.IntegerField(verbose_name='Semana 1')),
                ('segundaSemana', models.IntegerField(verbose_name='Semana 2')),
                ('terceraSemana', models.IntegerField(verbose_name='Semana 3')),
                ('cuartaSemana', models.IntegerField(verbose_name='Semana 4')),
            ],
            options={
                'verbose_name': 'Octubre',
                'verbose_name_plural': 'Octubre',
            },
        ),
        migrations.CreateModel(
            name='Septiembre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('primeraSemana', models.IntegerField(verbose_name='Semana 1')),
                ('segundaSemana', models.IntegerField(verbose_name='Semana 2')),
                ('terceraSemana', models.IntegerField(verbose_name='Semana 3')),
                ('cuartaSemana', models.IntegerField(verbose_name='Semana 4')),
            ],
            options={
                'verbose_name': 'Septiembre',
                'verbose_name_plural': 'Septiembre',
            },
        ),
    ]
