# Generated by Django 4.1.3 on 2022-11-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAIU_DATOS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agosto',
        ),
    ]
